const data = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    USER_ADD_NEW: "USER_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
    DEFAULT: ""
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    USER_DELETE: "USER_DELETE",
  },
});

export default data;
